### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by Yamasaki0401** [Yamasaki0401/protospace-38853#1]
https://protospace-38853.onrender.com

**Comment by snkw-works** [comment]
@Yamasaki0401 さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）

**Comment by Yamasaki0401** [comment]
ご確認ありがとうございました。
